name: Merge Momo Config

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 0 点 UTC 执行（北京时间 8 点）
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Merge configs
        run: python merge.py

      - name: Commit and push merged file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add merged_momo.json
          git commit -m "Auto merge configs" || echo "No changes to commit"
          git push
